### ISSUE TITLE
maf_data is not a valid parameter for GAMBLR.data::get_ssm_by_region

### ISSUE THREAD

**Issue by mattssca** [morinlab/GAMBLR.data#37]
For some reason, the `maf_data` parameter in `get_ssm_by_region` did not survive the migration and conversion into the GAMBLR.data equivalent version of this function. This was discovered when running the vignettes and helpfully informed with the very handy `check_excess_param` helper function.

This parameter might not be very useful for the GAMBLR.data version of this function (since it's loading the bundled MAF). But if the user wish to provide a maf of their own for subsetting, the function should accept this.

The error was discovered in `ashm_rainbow_plot`, since this function internally calls `get_ssm_by_region` and expects the `maf_data` parameter if a maf is provided to the plotting function in the first place. 

Self-assigning this issue, but posting here for tracking purposes. 

```
> ashm_rainbow_plot(mutations_maf = my_mutations,
+                   drop_unmutated = TRUE,
+                   metadata = fl_dlbcl_metadata,
+                   hide_ids = TRUE,
+                   bed = mybed,
+                   region = region,
+                   classification_column = "pathology",
+                   custom_colours = c("FL" = "#EA8368", "DLBCL" = "#479450"))
Error:  You have given one or more unsupported or deprecated argument to  get_ssm_by_region . Please check the documentation and spelling of your arguments.
Offending argument(s): maf_data
```

**Comment by Kdreval** [comment]
Thanks!
