### ISSUE TITLE
bundling ashm data with the package

### ISSUE THREAD

**Issue by Kdreval** [morinlab/GAMBLR.data#51]
The samples already released with the publications should have their mutations in the ashm regions released with he package. The mutations should be provided in both projections (grch37 and hg38) regardless of the original genome build they are released initially.
This update should allow get_ssm_by_regions return the mutations in the ashm sites.
The origin of variants should be production SLMS-3 calls.

**Comment by vladimirsouza** [comment]
Solved in [this](https://github.com/morinlab/GAMBLR.data/pull/53) PR.
