### ISSUE TITLE
The Pipeline column of bundled variant calls is not up-to-date

### ISSUE THREAD

**Issue by Kdreval** [morinlab/GAMBLR.data#52]
Some of the variants obtained from the supplemental materials of the papers are obtained before the SLMS-3 and GAMBL/GAMBLR  era. Nevertheless, when the variants are bundled with the package, they are all assigned SLMS-3 in the Pipeline column, which is misleading. This should be corrected in the following way:
1. The published variants should have Publication in the `pipeline` column of the returned maf
2. The same samples should have SLMS-3 variants released in both grch37 and hg38 projections
3. The get_coding_ssm and similar functions should start supporting the method argument and return SLMS-3 calls as default, but optionally return the publication calls

More details in this [Slack](https://morinlabsfu.slack.com/archives/C0224H120CU/p1705520412470399) thread

**Comment by vladimirsouza** [comment]
Solved in [this](https://github.com/morinlab/GAMBLR.data/pull/53) PR.
