### ISSUE TITLE
Finish GAMBLR child repos and update documentation

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR.data#54]

**Comment by rdmorin** [comment]
I know it's been a long haul but let's try to get this process finished so the main GAMBLR Readme is in sync with our current structure of the repositories.

**Comment by Kdreval** [comment]
this is done with the PR [#250](https://github.com/morinlab/GAMBLR/pull/250) and is now on GAMBLR master

**Comment by Kdreval** [comment]
Closing as completed
