### ISSUE TITLE
get_coding_ssm_status is missing some features

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR.data#58]
I noticed the include_silent option is missing from GAMBLR.data::get_coding_ssm_status but is in GAMBLR.results. I suppose this is because it's assumed that nobody would want to use this. I'm curious if it should be added. The use case I'm envisioning is including that information for aSHM targets.

**Comment by rdmorin** [comment]
Now that I've looked at the code, maybe the default functionality is actually using Silent variants alongside the coding variants. If so, this needs to be fixed and made optional. 

```
coding_ssm <- maf_data %>% dplyr::filter(Variant_Classification %in% 
        c("Frame_Shift_Del", "Frame_Shift_Ins", "In_Frame_Del", 
            "In_Frame_Ins", "Missense_Mutation", "Nonsense_Mutation", 
            "Nonstop_Mutation", "Silent",  #silent variants are being used?
             "Splice_Region", "Splice_Site", 
            "Targeted_Region", "Translation_Start_Site"))
```

**Comment by Kdreval** [comment]
Yes they are included by default - but I'll make this optional 👍

**Comment by rdmorin** [comment]
Let's chat in Slack about how we might be able to improve how both functions deal with silent mutations. Would be nice if we could have a behaviour that handles certain genes differently.

**Comment by Kdreval** [comment]
This is now implemented in both [GAMBLR.data](https://github.com/morinlab/GAMBLR.data/pull/56) and [GAMBLR.results](https://github.com/morinlab/GAMBLR.results/pull/42) version.
Closing this as completed
