### ISSUE TITLE
Object 'colour_codes' not found

### ISSUE THREAD

**Issue by mattssca** [morinlab/GAMBLR.data#7]
When testing `get_colours` (using the examples in the docs), I get an error message returned saying colour_codes are missing. This error message is repeated for all examples listed in the docs. Maybe I am running the function the wrong way, or the colour-specific functions are not ready to be tested yet?

```
> GAMBLR.data::get_colours(show_available = TRUE)
Error in dplyr::filter(colour_codes, is.na(is_alias)) : 
  object 'colour_codes' not found
```

**Comment by Kdreval** [comment]
The issue has now been resolved in [this](https://github.com/morinlab/GAMBLR.data/commit/82c051dd23750e4474613b05d7ff6ce173c19ac9) commit.
