### ISSUE TITLE
The badge README.md doesn't show up

### ISSUE THREAD

**Issue by vladimirsouza** [morinlab/GAMBLR.data#78]
[This line](https://github.com/morinlab/GAMBLR.data/blob/d6035fe737abe4ccb5e0bf132ee71475681d5a5f/README.md?plain=1#L1) in README.md, which should add a badge, is not working.
```
![](https://github.com/morinlab/GAMBLR.data/actions/workflows/build_check.yml/badge.svg)
```

**Comment by Kdreval** [comment]
Thanks for reporting!
This `yml` vs. `yaml` issue, now fixed in [this](https://github.com/morinlab/GAMBLR.data/commit/d3aaa980acf8b1332a69a26523ec536a4204c71b) commit.
