### ISSUE TITLE
Version parameter description is missing from get_genes

### ISSUE THREAD

**Issue by mattssca** [morinlab/GAMBLR.data#8]
As the title suggests, this parameter is missing from the documentation. I would like to see the different acceptable values detailed here. Currently, I have to read the code of the function to figure out what I can use for this parameter.

**Comment by Kdreval** [comment]
This has now been fixed in [this](https://github.com/morinlab/GAMBLR.data/commit/7ae26715bdc67380d2a292cc4c015abba3813f87) commit.
