### ISSUE TITLE
Feature request: DLBCL90 gene lists

### ISSUE THREAD

**Issue by lkhilton** [morinlab/GAMBLR.data#98]
Would it be straightforward to integrate the gene lists found here into this repo? 

`/projects/dscott_prj/CCSRI_1500/shared/ref/DLBCL90`

**Comment by Kdreval** [comment]
easy to add - need to gather documentation. Some particular are more interesting than the others or all 5 are needed?
```
COO15nano.xlsx  DHITsig30nano.xlsx  DLBCL90.txt  houseGene13nano.xlsx  PMBL30nano.xlsx
```

**Comment by lkhilton** [comment]
I think just the DLBCL90.txt file is needed. Let me add ENSG IDs to it before you proceed.

**Comment by lkhilton** [comment]
OK it now is updated with all the IDs that map to our salmon transcriptome reference. What documentation do you need, how can I help with that? `/projects/dscott_prj/CCSRI_1500/shared/ref/DLBCL90/DLBCL90_ENSG.txt`

**Comment by Kdreval** [comment]
I can definitely add these!
The documentation is just a brief description of the columns, similar to this: https://github.com/morinlab/GAMBLR.data/blob/c2003692bf75a4263c882e37464df0baafb2570e/R/data.R#L1-L14
